name: Notify Telegram on PR

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          ARGS="-d chat_id=${TELEGRAM_CHAT_ID} \
                -d text=📣 New PR by ${PR_AUTHOR}: *${PR_TITLE}*%0A🔗 ${PR_URL} \
                -d parse_mode=Markdown"

          if [ -n "${TELEGRAM_THREAD_ID}" ]; then
            ARGS="$ARGS -d message_thread_id=${TELEGRAM_THREAD_ID}"
          fi

          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage $ARGS
